[project]
name = "moding_vs_pandas"
version = "0.1.0"
description = "This sample code illustrates how Modin* accelerates the performance of Pandas for computational operations on a dataframe."
authors = [
    {name = "Copyright © 2020 Intel Corporation"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "modin[all]>=0.32.0",
    "numpy>=2.2.3",
]
[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
]
